server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:demo;Mode=Oracle
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
#    database-platform: org.hibernate.dialect.
